### ISSUE TITLE
Failed to ping target host: socket: permission denied

### ISSUE THREAD

**Issue by jkuj6** [librespeed/speedtest-cli#12]
Hi,

Since today, i have been having issues (from whichever PC i test in the world)
I try normal: `Librespeed/librespeed-cli` and it just hangs with:
```
Retrieving server list from https://librespeed.org/backend-servers/servers.php
Selecting the fastest server based on ping
```
Then i try: `Librespeed/librespeed-cli --debug` and then it shows errors:
```
Failed to ping target host: socket: permission denied
Will try TCP ping
Failed to ping target host: socket: permission denied
Will try TCP ping
Failed to ping target host: socket: permission denied
Will try TCP ping
```

Something wrong with the server being pinged?

The website however isnt giving these issues.  Not sure what is wrong? but it is definitely not on my side.

**Comment by maddie** [comment]
Under Linux, sudo is required to ping via ICMP. It's not a big deal actually, but I think the error messages can be improved. Please leave this issue open and I'll think of a way to handle this better.

Thanks for your report!

**Comment by jkuj6** [comment]
@maddie i tried with sudo, (i even sudo su and then tried) still same error messages would run forever in a loop.
Not sure if you understand what the actual issue is though, **since yesterday** i try and do a speedtest after connecting to vpn servers and it hangs there, only very seldom does it continue to find a server.  This never used to be an issue previously.
Do you think your servers are blocking pings from vpn providers?

**Comment by maddie** [comment]
So if you use the cli without VPN, it works?

If so, it could probably be the configuration problem of your VPN software, or restrictions from your VPN provider. The servers don't know which connections are from VPN providers, so it's unlikely that they will block them.

**Comment by jkuj6** [comment]
> So if you use the cli without VPN, it works?

I tried cli without vpn and it still errors most times. (tried this yesterday from different countries and no vpn provider)

Now i tried a speedtest again from a vpn provider from a completely different country than what i tried previously and the speedtest went through.  Why do you think the vpn provider would block speedtests on their servers though? Their app shows the servers that are not overloaded, but i dont use their app so ive always done a speedtest.  But why would they block it though?

**Comment by maddie** [comment]
I'm not really sure, but it's possible that the ICMP ping/TCPing just timed-out to some of the servers, possibly because of the connection between your VPN exit node and the speed test server.

Still, I think this confusion is caused by the repeated error messages, I'll have to find a way to improve this.

**Comment by jkuj6** [comment]
Yea only with --debug, otherwise if you dont use --debug, then it will just hang there forever with no error message.
Im not sure why it would timeout though.
I think if you find a way to improve the error message, maybe then we can see what the real issue issue is between pinging of the servers.
Maybe also check if the servers have been blocking random icmp requests?  I doubt the vpn provider would be blocking outgoing icmp requests.

**Comment by maddie** [comment]
It shouldn't hang forever, it just takes a long time to ping all the servers if the connection is slow. You can leave it running to see if it finishes, if possible.

Some of the servers do block ICMP pings, but it will fall back to HTTP ping automatically (like the web frontend does) if that fails. Beside, the error message you're seeing (`permission denied`) comes from your OS, not the server.

**Comment by jkuj6** [comment]
> the error message you're seeing (`permission denied`) comes from your OS, not the server.

but i tried running librespeed with sudo as well, and i even sudu su and tried it. On any PC with Xubuntu 18.04 i try it on, it gives those permission denied errors, how is it from my OS?  Can you try reproduce this on Ubuntu and see please?

**Comment by maddie** [comment]
The servers will not give "permission denied" as an error. And please see the below links for your information.

https://github.com/go-ping/ping#note-on-linux-support
https://github.com/go-ping/ping/issues/4
https://github.com/go-ping/ping/issues/24

Considering the messages only print when `--debug` enabled, the current behavior will be retained as-is for now.
