### ISSUE TITLE
Result of download speed is incorrect.

### ISSUE THREAD

**Issue by harryhack** [librespeed/speedtest-cli#13]
![Screenshot 2020-10-16 183422](https://user-images.githubusercontent.com/27751880/96253734-54839d00-0fde-11eb-8bff-7c4e4ae4da51.png)
Hi everyone,
I had finished installing Librespeedtest-cli on debian 9. But the result of download speed is too low. Can you help me ?

**Comment by adolfintel** [comment]
Does the web version work on that server?

**Comment by harryhack** [comment]
> Does the web version work on that server?
Version web : Apache/2.4.6 (CentOS) PHP/5.4.16.
When I run speedtest on web, the result is correct. But incorrect when run librespeedtest-cli on debian 9.

**Comment by maddie** [comment]
It's essentially doing the same thing as the web version, what results do you get in the web version?

**Comment by harryhack** [comment]
> 
> 
> It's essentially doing the same thing as the web version, what results do you get in the web version?
![ảnh](https://user-images.githubusercontent.com/27751880/96312841-a3f5b780-1036-11eb-8227-e7d39938e0d2.png)

This is result in the web version. Download and upload are same same. 
This result is correct, because I am using bandwidth 60 MB/s.

**Comment by sl4m75** [comment]
I have this issue too, tested using the same server:
![1609716285](https://user-images.githubusercontent.com/66081366/103491413-d2648100-4e34-11eb-89b5-e8d5c06216b1.png)
![1609716313](https://user-images.githubusercontent.com/66081366/103491415-d4c6db00-4e34-11eb-99b5-8394ad3ac80f.png)

**Comment by bensteinberg** [comment]
I think I'm seeing this, too. Web interface shows download of 120Mbps, upload of around 6; CLI shows `"upload":5.8,"download":67.08`. The system is a Raspberry Pi 3B+ running Debian buster.

**Comment by bensteinberg** [comment]
I'm guessing this is due to download speed being a `float64` on a 32-bit machine, at https://github.com/librespeed/speedtest-cli/blob/master/speedtest/helper.go#L83

**Comment by harryhack** [comment]
> 
> 
> I'm guessing this is due to download speed being a `float64` on a 32-bit machine, at https://github.com/librespeed/speedtest-cli/blob/master/speedtest/helper.go#L83

Maybe ! Can't you help me ?

**Comment by maddie** [comment]
`float64` shouldn't be a problem in 32-bit machine, or this will be a major portability problem in Go.

You can try changing it to `float32` and compile it to see if it works.

**Comment by bensteinberg** [comment]
Thanks, @maddie. That makes sense about portability. I did an experiment and recompiled, but the behavior was the same: correct download speed on amd64, wrong speed on armv7l.

**Comment by harryhack** [comment]
Can't I use file .zip to get result of down/upload  ?
Anyone help me please ?

**Comment by maddie** [comment]
@harryhack What do you mean by use file .zip?

**Comment by harryhack** [comment]
> 
> 
> @harryhack What do you mean by use file .zip?

Yes @maddie . I need use file .zip to test down/upload. Can you help me ?

**Comment by maddie** [comment]
@harryhack I'm sorry, I'm afraid that I don't understand what you're asking 😅

**Comment by harryhack** [comment]
> 
> 
> @harryhack I'm sorry, I'm afraid that I don't understand what you're asking 😅

@maddie I know that librespeed use file garbage.php to create file random.dat . This file is used to test download speed.
But I need to use file .zip to do that.

**Comment by maddie** [comment]
I'm afraid that's out of the scope of this project, or even librespeed.

The simplest way that you can achieve this is by serving a big .zip file on your web server, and use `curl` to check the speed.

**Comment by harryhack** [comment]
> 
> 
> I'm afraid that's out of the scope of this project, or even librespeed.
> 
> The simplest way that you can achieve this is by serving a big .zip file on your web server, and use `curl` to check the speed.

@maddie thank you.

**Comment by adolfintel** [comment]
@harryhack @maddie If you want to use curl to check the speed, you can do `curl yourdomain.com/backend/garbage.php?ckSize=1024` to download 1gb of garbage data (max allowed with a single connection).

**Comment by harryhack** [comment]
> 
> 
> @harryhack @maddie If you want to use curl to check the speed, you can do `curl yourdomain.com/backend/garbage.php?ckSize=1024` to download 1gb of garbage data (max allowed with a single connection).

@adolfintel Can you explain about item ckSize ?

**Comment by harryhack** [comment]
@adolfintel Thank for your help. 
But I need to use file compression (ex file extension .zip) instead of file random.dat (garbage create this file).
Any ideal for this ?

**Comment by adolfintel** [comment]
ckSize is the size of the generated random.dat in megabytes, max 1024.

Using a zip file makes no difference, you can simply rename random.dat to random.zip if you want.
