### ISSUE TITLE
[Suggestion] Add option to skip certificate validation

### ISSUE THREAD

**Issue by AlphaJack** [librespeed/speedtest-cli#16]
I would like to measure how much bandwidth I can trasmit using my personal VPN. I would like to carry my tests behind a HTTPS reverse proxy, so I need NginX and its certificate. Unfortunatly it doesn't seem to work, my guess is because of failed certificate validation (I can't see any verbosity option):

`cat server.json`
```json
[
 {
  "id": 1,
  "name": "Librespeed test",
  "server": "https://10.1.1.1/",
  "dlURL": "librespeed/garbage.php",
  "ulURL": "librespeed/empty.php",
  "pingURL": "librespeed/empty.php",
  "getIpURL": "librespeed/getIP.php"
  }
]
```

`librespeed-cli --local-json server.json`
```
Using local JSON server list: server.json
Selecting the fastest server based on ping
No server is currently available, please try again later.
```

If I change "server" with "https://example.org/" the test runs correctly, but it returns results from normal connection, I.E. not inside the VPN. I can also succesfully test with "server" set to "http://10.1.1.1/", as the server instance is also available without the reverse proxy.

---

Curl has an option to skip certificate validation:
`curl https://10.1.1.1/librespeed/`
```
curl: (60) SSL: no alternative certificate subject name matches target host name '10.1.1.1'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

`curl -k https://10.1.1.1/librespeed/`
```html
<!doctype html>
 <!-- [...] -->
</html>
```

**Comment by maddie** [comment]
@AlphaJack I've pushed a commit 4676b26 adding the option `--skip-cert-verify`, can you build it locally and try if it works for you?

**Comment by AlphaJack** [comment]
Thank you, it works now.
