### ISSUE TITLE
[RFE] OpenWrt?

### ISSUE THREAD

**Issue by atrent** [librespeed/speedtest-cli#18]
Would it be possible to cross compile it for OpenWrt?

**Comment by maddie** [comment]
Yes, just download the appropriate binary from the releases page.

**Comment by atrent** [comment]
Can you elaborate better?
I cannot find an openwrt binary on the release page and I'm dubious (that's why I asked) about a cross compilation.
Thank you

**Comment by maddie** [comment]
You can see the file names are like this:

`librespeed-cli_1.0.7_linux_armv7.tar.gz`

`1.0.7` is the version.
`linux` is the OS.
`armv7` is the architecture.

You need to download the corresponding OS/arch binary to use on your router.

**Comment by atrent** [comment]
thanks, it (almost) works:

# ./librespeed-cli 
Retrieving server list from https://librespeed.org/backend-servers/servers.php
Retry with /.well-known/librespeed
Error when fetching server list: Get "https://librespeed.org/backend-servers/servers.php/.well-known/librespeed": x509: certificate signed by unknown authority
Terminated due to error

but I think it could be a problem on the website, not on libraries in my router

**Comment by maddie** [comment]
Install `ca-certificates` with opkg.

**Comment by atrent** [comment]
now it works, thanks again

**Comment by varac** [comment]
I just opened #44 for openwrt MIPS support

**Comment by paper42** [comment]
librespeed-cli is now available in OpenWrt 21.02 and newer versions with opkg
