### ISSUE TITLE
--local-json

### ISSUE THREAD

**Issue by look-at-that** [librespeed/speedtest-cli#21]
Hi,
I'm having troubles using librespeed-cli  against a local installation of Ookla Server for testing purposes.

`./librespeed-cli --local-json ./servers.json --server 1
Using local JSON server list: ./servers.json
Selected server: Localhost [localhost]
Selected server Localhost (localhost) is not responding at the moment, try again later`

Here's the content of servers.json

`[{
    "id": 1,
    "name": "Localhost",
    "server": "http://localhost:8080/speedtest/",
    "dlURL": "download",
    "ulURL": "upload",
    "pingURL": "hello",
    "getIpURL": "getip"
  }]
`

Trying wget to connect to each of the endpoints defined in json file results in http 200 / OK

`wget http://localhost:8080/speedtest/getip` -> 200 OK

Am I missing something?

Thanks!

**Comment by adolfintel** [comment]
You can't use an ookla server for this, it's a totally different thing.
Maybe you were looking for this: https://github.com/sivel/speedtest-cli
