### ISSUE TITLE
IPv6 test to LibreSpeed server not working

### ISSUE THREAD

**Issue by natzlob** [librespeed/speedtest-cli#22]
When running the librespeed test with --ipv6 command line option, the result is ```Error when fetching server list: Get https://librespeed.org/backend-servers/servers.php/.well-known/librespeed: dial tcp6 [2a01:4f8:c17:xxxx::1]:443: connect: cannot assign requested address
Terminated due to error``` on one linux machine, and ```Error when fetching server list: Get "https://librespeed.org/backend-servers/servers.php/.well-known/librespeed": dial tcp6 [2a01:4f8:c17:xxxx::1]:443: connect: no route to host
Terminated due to error``` on a mac

**Comment by Perflyst** [comment]
Do you have an IPv6 address? `2a01:4f8:c17:14ac::1` is the IP of the librespeed.org server

**Comment by natzlob** [comment]
Yes, I have an IPv6 address on my machine, and ping6 to the librespeed.org IPv6 address also does not work. Are there only some of the servers around the world that have IPv6 enabled?

**Comment by Perflyst** [comment]
> ping6 to the librespeed.org IPv6 address also does not work

It works for me (`ping -6 librespeed.org` and `curl -6 -I https://librespeed.org`) from multiple locations.

> Are there only some of the servers around the world that have IPv6 enabled?

Not all librespeed.org backend testservers have IPv6 but librespeed.org itself definitely has IPv6

**Comment by natzlob** [comment]
The curl works for me but not the ping

**Comment by Perflyst** [comment]
pings are not blocked on librespeed.org
can you ping other hosts? can you please provide a traceroute or mtr?

**Comment by JoKr4** [comment]
I had the same issue.

Turned out it was a bad shorewall6 policy / ip6tables rule

@natzlob
Maybe you need to check your Firewall

**Comment by natzlob** [comment]
Thanks
