### ISSUE TITLE
bytes_received consistently more than bytes_sent

### ISSUE THREAD

**Issue by natzlob** [librespeed/speedtest-cli#24]
I think there msut be a mistake because using the --json flag for results I consistently see that bytes_received is more than bytes_sent, so the lost bytes is negative. Have these values been returned the wrong way around in the json construction?

**Comment by maddie** [comment]
I'm not sure what you mean by `bytes_received` and `bytes_sent`. Can you elaborate?

**Comment by natzlob** [comment]
When you run librespeed-cli with --json option,
e.g. `~  librespeed-cli --json`

```{"timestamp":"2021-03-16T13:11:33.548884+02:00","server":{"name":"London, England (Clouvider)","url":"http://lon.speedtest.clouvider.net/backend"},"client":{"ip":"197.89.195.48","hostname":"197-89-195-48.dsl.mweb.co.za","city":"Cape Town","region":"Western Cape","country":"ZA","loc":"-33.9258,18.4232","org":"AS10474 Dimension Data (Pty) Ltd - Optinet","postal":"7945","timezone":"Africa/Johannesburg"},"bytes_sent":39321600,"bytes_received":80420607,"ping":152,"jitter":4.07,"upload":20.16,"download":41.24,"share":""}```
the values for bytes_sent is less than bytes_received, as you can see in this actual output. This does not make sense, because the number of bytes received cannot be more than what was sent

**Comment by maddie** [comment]
`bytes_sent` is the byte count for the `upload` action, and `bytes_received` is for download.

They don't correlate with each other in any way.
