### ISSUE TITLE
How are multiple requests to a single server handled?

### ISSUE THREAD

**Issue by natzlob** [librespeed/speedtest-cli#25]
What is the mechanism or technology used to handle having many requests to the same server, and is there a limit on the number of simultaneous requests to one server, and what is that limit/capacity?

**Comment by maddie** [comment]
It uses `go routines` to initiate HTTP requests.

The CLI itself doesn't limit how many concurrent requests can be made, and the current default setting is `3`. You can change this with `--concurrent` flag. The actual limit/capacity would most likely be on the server-side.

**Comment by natzlob** [comment]
I wanted to know how you handle it on the librespeed server side. What is the limit on each of the librespeed-hosted servers?

**Comment by maddie** [comment]
> I wanted to know how you handle it on the librespeed server side. What is the limit on each of the librespeed-hosted servers?

This depends on your server's connection and configuration. Librespeed backend does not have an artificial limitation.

**Comment by natzlob** [comment]
Thanks, but what is the actual physical limit, when requests by hosts will get rejected? Will your servers be able to handle it if suddenly thousands more requests from as many different hosts are made to them every 10-20min?

**Comment by adolfintel** [comment]
That depends on your server, if it has enough bandwidth and processing power there is no artificial limit imposed by LS.
