### ISSUE TITLE
"private" Server xxx is not responding at the moment. Try again later

### ISSUE THREAD

**Issue by fmolinelli** [librespeed/speedtest-cli#27]
Hi, I have a problem with speedtest-cli not contactibg local private librespeed host,

- set up a standalone librespeed server as a container on a synology NAS, running as http://192.168.1.220:80
- tried from several web client on local networkand it works fine
- set up an ubuntu desktop client as 192.168.1.24: web librespeed to local server works ok
- on the same ubuntu desktop installed librespeed-cli_1.0.7_linux_amd64.tar.gz: tested with generic librespeed internet hosts and works fine
- set up in ubuntu desktop a servers-json file with local librespeed server info, 
-[
  {
    "id": 1,
    "name": "PHP Backend",
    "server": "//192.168.1.220/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL" :"empty.php",
    "getIpURL": "getIP.php"
  }
]

- launched librespeed against local server
labadmin@UBUDSK2004:~/librespeed$ sudo ./librespeed-cli --local-json servers-json --server 1
[sudo] password for labadmin:
Using local JSON server list: servers-json
Selected server: PHP Backend [192.168.1.220]
Selected server PHP Backend (192.168.1.220) is not responding at the moment, try again later
labadmin@UBUDSK2004:~/librespeed$

-  ping from 192.168.1.24 to 192.168.1.220 are ok
-  curl from 192.168.1.24 to http://192.168.1.200 returns the librespeed landing page.
-  
where i made the mistake installing/configuring librespeed-cli?

Thank you very much!

**Comment by maddie** [comment]
Make sure the URLs in JSON is correct, i.e. `dlURL`, `ulURL`, `pingURL` and `getIpURL`.

**Comment by fmolinelli** [comment]
[SOLVED]

Hi Maddie,

thank you so much for the hint: hi tcpdump'd the _working_ web session and found that the URLS have to be expressed with a prepended "backend/" like "backend/empty.php".

now it works!

Regards
