### ISSUE TITLE
remote server is down - id request per backend

### ISSUE THREAD

**Issue by willemijns** [librespeed/speedtest-cli#3]
Hello,

```
Retrieving LibreSpeed.org server list
Selecting the fastest server based on ping
Selected server: Helsinki, Finland (1) (Hetzner) [fi1.backend.librespeed.org]
Selected server Helsinki, Finland (1) (Hetzner) (fi1.backend.librespeed.org) is not responding at the moment, try again later

```

can you add an UID for every server to force or exclude specific servers ?
maybe adolfintel need to update the server code ?

**Comment by Perflyst** [comment]
> can you add an UID for every server to force or exclude specific servers?

This is planned and will most likely be added soon.

> is not responding at the moment, try again later

According to our monitoring this backend was not down, though it may had a longer response time. A solution to avoid these cases (webserver down, but server and icmp ping working) is discussed internally.

**Comment by maddie** [comment]
@willemijns For now, you can use `--list` to get the IDs for each server, and use multiple `--exclude` option to exclude the servers.

**Comment by willemijns** [comment]
ok great i will test later ;)

**Comment by willemijns** [comment]
i will wait prebuild ;) v1.0.4 @maddie maddie released this 4 days ago · 2 commits to master since this release

**Comment by maddie** [comment]
This feature is included from v1.0.0, you can test it now.

**Comment by maddie** [comment]
@willemijns Is this issue resolved for you?

**Comment by willemijns** [comment]
yes. i close ;)
