### ISSUE TITLE
about github name

### ISSUE THREAD

**Issue by willemijns** [librespeed/speedtest-cli#4]
Hello,

Is speedtest-cli is the name to keep for the main github URL https://github.com/librespeed/speedtest-cli ? ^^

**Comment by willemijns** [comment]
it is to avoid mixes with other (closed) project.

**Comment by maddie** [comment]
The project name is meant to be consistent with the `speedtest` backend project. The binary name isn't the same, I think that should suffice.

Closing this issue for now.
