### ISSUE TITLE
Upload test data management and storage

### ISSUE THREAD

**Issue by natzlob** [librespeed/speedtest-cli#40]
Hi. How is the uploaded data for the Upload test managed? Where is it stored? Does LibreSpeed create a temp file for this on the device, which it then deletes, or the device on which the test is running will periodically need to clean this out?

**Comment by maddie** [comment]
The uploaded data is randomly generated on each run, stored in memory, and discarded on exit. There's no temp file on disk, so you don't have to do cleanups.

**Comment by natzlob** [comment]
Thanks 👍
