### ISSUE TITLE
Speedtest backend in Prague

### ISSUE THREAD

**Issue by melnijir** [librespeed/speedtest-cli#45]
There is another librespeed instance available:

https://speedtest.cesnet.cz

frontend is just a slightly modified, but backend is exactly the same, so it could be used by speedtest-cli:

```
[
  {
    "id": <ID>,
    "name": "Prague, Czech Republic (CESNET)",
    "server": "//speedtest.cesnet.cz/backend/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "CESNET",
    "sponsorURL": "https://www.cesnet.cz"
  }
]
```

server is connected via 10Gbps link and should be stable and online for a long time (current uptime is more than 1 year).

**Comment by maddie** [comment]
Could you please re-open this issue in [librespeed/speedtest](https://github.com/librespeed/speedtest)?

Thanks!
