### ISSUE TITLE
results not writing to stdout

### ISSUE THREAD

**Issue by zocker-160** [librespeed/speedtest-cli#5]
when I run librespeed-cli and try to pipe the output into a file, I get very inconsistent results, some parts can be piped and some cannot.

This is very confusing, expected behavior would be, that all of the output is STDOUT which can be piped into a file.

![Screenshot_20200331_105536](https://user-images.githubusercontent.com/36563538/78007610-d06a1080-733e-11ea-91e9-4cf79a07b272.png)

**Comment by maddie** [comment]
Hi,

The usual output isn't meant for piping into a file since it has moving parts (the progress spinner).

If you're piping the results (not using `--csv` or `--json`), consider use with the `--simple` option.

**Comment by maddie** [comment]
Hmm, I see your point. Currently, the output are sent to `stderr` instead. I will fix this soon.

**Comment by maddie** [comment]
Should be fixed in v1.0.6

**Comment by zocker-160** [comment]
works as expected now, thank you! :+1:
