### ISSUE TITLE
Any compatibility issues between librespeed and speedtest-cli?

### ISSUE THREAD

**Issue by vhaasteren** [librespeed/speedtest-cli#7]
I have a local librespeed server running, and I'm trying to connect my librespeed/speedtest-cli unit (using the --local-json option) to it, and I always get the message that "No server is currently available, please try again later.". If I add any of the 'official' servers to the local json my own speedtest-cli does manage to connect to it. However, my own server is reachable and the site loads just fine (and runs tests). I tried hosting my librespeed server remote as well on my VPS (with domain name, both http and https) with the same results. I can run the site, but not through the cli.

The librespeed server is the docker edition, and I pulled it from linuxserver and built from the latest Dockerfile on github. As for the speedtest-cli, it's just the latest from github.

I have tried all the combinations in the local json (https, http, //, escaping the '/', adding the --secure and not, running my server through https and http, verified domain names...) but always the same message.

Any hints on where to look to figure this out?

**Comment by maddie** [comment]
Can you post your JSON file? The CLI should work with all backends.

Also, try running with `--debug` flag

**Comment by vhaasteren** [comment]
Sure, posted below. Note that the librespeed2.mycomain.com resolves into a local (192.168.x.x) address, if that matters. There is a difference between the debug output when I do and do not have the backends running. Example when not running:

Error checking for server status: Get http://librespeed2.mydomain.com/empty.php: dial tcp 192.168.x.x:80: connect: connection refused
Server Home (same machine) (RvH) (librespeed2.mydomain.com) doesn't seem to be up, skipping

When running the backend:
Server Home (same machine) (RvH) (librespeed2.mydomain.com) doesn't seem to be up, skipping

Any ideas?

Thanks!


[
    {
        "name":"VPS (remote)",
        "server":"\/\/mydomain.com:8084\/",
        "dlURL":"garbage.php",
        "ulURL":"empty.php",
        "pingURL":"empty.php",
        "getIpURL":"getIP.php"
    },
    {
        "name":"Home (same machine) (RvH)",
        "server":"\/\/librespeed2.mydomain.com\/",
        "dlURL":"garbage.php",
        "ulURL":"empty.php",
        "pingURL":"empty.php",
        "getIpURL":"getIP.php"
    },
  {
    "name": "Server (local machine)",
    "server": "\/\/192.168.x.x:8084\/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  },
  {
    "name": "Same machine, routed through traefik",
    "server": "https://librespeed.mydomain.com/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  },
  {
    "name": "Docker hostname (http)",
    "server": "http://librespeed/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  }
]

**Comment by maddie** [comment]
What does accessing `empty.php` on your backend returns?

Try `curl -vvv http://librespeed.mydomain.com/empty.php` and see what returns.

The correct behavior should be return nothing, with status code 200.

**Comment by vhaasteren** [comment]
Thanks for the help! Interesting. I'm getting a 404. I'm running the linuxserver docker for this run, but I've also tried just building the Dockerfile from the github repo:  https://github.com/librespeed/speedtest

If I just place "http://librespeed2.mydomain.com/" in the browser I get to the testing site and can run tests...

Does this make any sense?

[ /home/librespeed-cli (traefik_v2) ] curl -vvv http://librespeed2.mydomain.com/empty.php
*   Trying 192.168.1.7:80...
* TCP_NODELAY set
* Connected to librespeed2.mydomain.com (192.168.1.7) port 80 (#0)
> GET /empty.php HTTP/1.1
> Host: librespeed2.mydomain.com
> User-Agent: curl/7.65.3
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Mon, 20 Apr 2020 01:37:31 GMT
< Server: Apache/2.4.38 (Debian)
< Content-Length: 288
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at librespeed2.mydomain.com Port 80</address>
</body></html>
* Connection #0 to host librespeed2.mydomain.com left intact

**Comment by maddie** [comment]
Hmm.. Is the Docker container behind a reverse proxy?

**Comment by vhaasteren** [comment]
Yes, traefik

**Comment by maddie** [comment]
It's weird that `empty.php` is returning 404 from the Docker container.

@adolfintel Federico, do you have any idea?

**Comment by adolfintel** [comment]
I'm not sure either. Is the docker container in single server or multi server mode?

**Comment by vhaasteren** [comment]
This should be fairly reproducible, right? Isn't this what docker was invented for? Here's my docker-compose. I've tried without the mem_limit, in case you are wondering about it.

`version: "2"

services:
    librespeed:
        image: linuxserver/librespeed
        container_name: librespeed
        hostname: librespeed
        restart: unless-stopped
        mem_limit: 64m
        environment:
            - TZ=America/Los_Angeles
            - PASSWORD=speedtest
        ports:
              - 8084:80
        networks:
            - st_ext
        labels:
            - "traefik.enable=false"

networks:
    st_ext:
        driver: bridge`

**Comment by adolfintel** [comment]
@vhaasteren I need to know if you're running the container in standalone mode, backend mode or frontend mode. If you're in standalone, empty.php will be in backend/empty.php (same for garbge.php)

**Comment by vhaasteren** [comment]
Oh...  well, that explains a lot. Yeah, if I request empty.php on http://mydomain.com/backend/empty.php then I do indeed get a status code 200.

Honestly, I didn't even realize there was such a thing as running in backend mode :)

So basically the solution is to update the server.json with a 'backend' prepended to the php files (or appended to the server link)?

Thanks!

**Comment by adolfintel** [comment]
You need to run it in backend mode for what you're trying to do

On April 20, 2020 8:01:11 PM GMT+02:00, Rutger van Haasteren <notifications@github.com> wrote:
>Oh...  well, that explains a lot. Yeah, if I request empty.php on http://mydomain.com/backend/empty.php then I do indeed get a status code 200.
>
>Honestly, I didn't even realize there was such a thing as running in backend mode :)
>
>So basically the solution is to update the server.json with a 'backend' prepended to the php files (or appended to the server link)?
>
>Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/librespeed/speedtest-cli/issues/7#issuecomment-616718716
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vhaasteren** [comment]
Ok, understood. Thank you so much for the help!

**Comment by vhaasteren** [comment]
So just to try I modified my server.json to below, and it worked also without setting the docker to multiserver mode 

[
{
"name":"Self-hosted Librespeed server",
"server":"//mydomain.com/backend/",
"dlURL":"garbage.php",
"ulURL":"empty.php",
"pingURL":"empty.php",
"getIpURL":"getIP.php"
}
]

**Comment by adolfintel** [comment]
Yes but that won't work in the browser (doesn't send CORS headers in standalone mode)

On April 20, 2020 8:47:40 PM GMT+02:00, Rutger van Haasteren <notifications@github.com> wrote:
>So just to try I modified my server.json to below, and it worked also without setting the docker to multiserver mode 
>
>[
>{
>"name":"Self-hosted Librespeed server",
>"server":"//mydomain.com/backend/",
>"dlURL":"garbage.php",
>"ulURL":"empty.php",
>"pingURL":"empty.php",
>"getIpURL":"getIP.php"
>}
>]
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/librespeed/speedtest-cli/issues/7#issuecomment-616741183
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maddie** [comment]
Closed due to inactivity.
