### ISSUE TITLE
why error  https://test.ustc.edu.cn/

### ISSUE THREAD

**Issue by aogg** [librespeed/speedtest-cli#89]
```
Using local JSON server list from stdin
Error when fetching server list: unexpected end of JSON input
Terminated due to error

```

```
git clone https://github.com/librespeed/speedtest-cli.git
cd speedtest-cli
 docker build -t librespeed-cli:latest .
 echo '[{"id": 1,"name": "a","server": "https://test.ustc.edu.cn/","dlURL": "garbage.php","ulURL": "empty.php","pingURL": "empty.php","getIpURL": "getIP.php"}]' | docker run --rm --name librespeed-cli librespeed-cli --local-json -

```

**Comment by xiaoliu** [comment]
two things causing the issue,
1. the server url for this should be "https://test.ustc.edu.cn/backend/" (but this is not the main reason, you'll find even if you change this, the speed test will still fail with using speedtest-cli)

2. (main reason) this speed test server is returning a non empty result ('not ustc') when hitting the pingURL, its checking for a header cookie to validate the test comes from a browser more or less which my guess is their way of preventing other clients using their test end point
